channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=24.0
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - psutil==5.9.0
  - scikit-learn==1.1.1
  - scipy==1.12.0
name: mlflow-env
